### ISSUE TITLE
Creating an archive results in a lot of padding at the end

### ISSUE THREAD

**Issue by thetrime** [SWI-Prolog/packages-archive#14]
By default libarchive pads the block to 10240 bytes unless you call 
```
archive_write_set_bytes_in_last_block(ar->archive, 1);
```
after creating the archive. This only happens if you use the callback-style handlers - if you write the file to disk directly then no padding is added.

This isn't technically a _bug_ - the file generated is still legal, however some decompressors (notably, the jar decompressor built into java, at least in java 1.8) fails to read them correctly.

Is there any reason not to change this? If no, I'll create a PR

**Comment by JanWielemaker** [comment]
I think it is ok to change this.  Would be nice to know why they do so?

**Comment by thetrime** [comment]
I think it's just for efficiency - the generated file is still well-formed, just bigger than it needs to be. Java assumes that if there is any padding then it must be in a comment record, but the actual file just contains null bytes. I'll file a PR in any case
