### ISSUE TITLE
unknown type name 'la_int64_t' when compiled against libarchive 3.1.2

### ISSUE THREAD

**Issue by anionic** [SWI-Prolog/packages-archive#22]
The commit of 18/Apr/2022 ("CLEANUP: Removed references to libarchive versions before 3.0.0a") altered the signatures of `ar_skip() and ar_seek()` to use the typedef `la_int64_t` instead of the macro `__LA_INT64_T` but this is not defined in libarchive 3.1.2

I suppose I might `s/la_int64_t/int64_t/` to get SWI-Prolog 8.5.11 onwards to build under CentOS 7? 

`yum update` is not offering us any updates to libarchive 3.1.2 release 14.e17_7 :-/

**Comment by JanWielemaker** [comment]
Seems to be the easiest way.   Updated.  CentOS 7 is EOL, so that is barely an argument.
